<a href="https://colab.research.google.com/github/dustindobry/AIMA/blob/Svenja-Stickinator/week_01_introduction_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI in Medical Applications

## Chapter 0: "Introduction to Python"

Welcome to the seminar, we're glad you've made it here!

Over the course of the following chapter, we will give you a quick introduction to Python, and some general tools you will probably find useful to know about. This tutorial is designed to be quick to complete. If you feel uncertain about some aspects of Python (maybe you're new to programming or find Python weird), that's no problem. There is a plethora of sources for Python online, and you can always come ask us.

Now for some general rules.

1) As people have different levels of prior knowledge about programming, some of you may find the following tasks to be extremely easy. If that is the case for you, you may skip to the end of the notebook. There are a couple of tasks which you should be able to solve by the end of this tutorial:
- At the end of Chapter 0.9
- In Chapter 0.10
- **Committing your results to GitHub is mandatory.** (see Chapter 0.11)
Since today is mostly going to be a tutorial session, the is exercise itself is not graded, you simply receive one point for committing your notebook to GitHub. Starting next week, all exercises will be graded.
2) *No question is stupid*. If you don't know how something works, step 1 is to try and formulate your problem as a google search, and see if someone else asked the same question that you have. Usually they have. If you still cannot find an answer, or the problem is difficult to google search, feel free to talk to any of the PhDs supervising the course. That's what we're here for. Similarly, if you have a question about something in these prepared notebooks, ask it. We are not perfect and neither are the tutorials, so chances are that some things warrant additional explanation by us, or are even a little wrong.
3) Experiment. Try to take apart the code and put it back together. The more you actually do instead of only read, the more will the solution stick in your memory. Counterintuitively, this is particularly true if you *don't* understand what the code you just executed actually does. One of the best ways to learn is to take apart someone elses code and reassemble it, or think of a small, private project that you want to do and try to realize it in Python. Learning by doing.
4) If you ever find yourself thinking "This should be a really common use case", it probably is. Try to express what you want in terms of Python lingo and you will almost certainly find what you are looking for on Google and Stackoverflow. Most of the time, it is even already a single function or class in a package you already have. Finding out about features in this way is basically the norm, rather than the exception.
5) If you manage a task partially but not fully, and your code doesn't quite run properly, no worries. You will probably receive more than 0 points anyway, and we can probably also tell you where the mistakes you made were and how to avoid them in the future. We won't bite.

In case you want to, you can turn on Autosave in Colab, so your progress is saved. You can execute this, and any other cell by pressing Shift+Enter, or by pressing the little play button next to it.

In [ ]:
%autosave 60

Autosaving every 60 seconds


### Chapter 0.1: "Variables and Built-ins"

Python is a high-level language, built on C. This means that in Python it is, usually, comparatively easy to get started and code *something* which works. The downside is that performance occasionally suffers a little bit. Most machine learning nowadays is done in Python, but the underlying code (that runs "under the hood" so to speak) is implemented in faster languages (C, C++, etc.). Thankfully, some very talented programmers have already done the hard part of creating extremely fast basic math operations running on the GPUs, and we only need to write the comparatively easy Python code. Eventually, the Python code actually makes use of their code, which means that we get the best of both worlds - easy code and fast/efficient implementation.

Let's check out some basics.

You can execute a block of code by selecting it with the mouse and pressing Shift + Enter, or by pressing the little play button on the top left corner of the block.

In [ ]:
# In Python, when we declare a variable, all we need to do is give it a name, and tell it what it is.
# Instead of explicitly requiring us to tell it what we have given it, Python infers the so-called type
# of the variable on its own.
#
# Python immediately knows that a is an integer, that b is a floating point number (in short: float),
# and that the my_pet variable is a string.

a = 1
b = 2.5
my_pet = "dog"

# We can look at almost anything (not images) in Python using the print() function.
# Here, we use it to tell us what the value of the variable is, and what the type of the variable is.

print(a)
print(type(a))

# A good thing to keep in mind is that both you and other people will read your code. This means that
# you want to keep it tidy:
# 1) If there is code that doesn't have anything to do with other code, maybe leave a blank line.
# 2) If you want to tell someone what you're doing, maybe write a comment (start the line with a '#') to
# explain what you are doing.
# 3) And, most importantly, if you create a variable, name it appropriately. For example, if you want to
# have a variable that contains your dog's name, Sparky:

x = "Sparky"        # Not a good name, because you won't remember what x stands for in a few days.
pet_name = "Sparky" # A very good name, because it is short, but tells you what it represents.
the_name_of_my_pet_whomst_i_love = "Sparky" # Not a good name, because it is far too long.

1
<class 'int'>


In [ ]:
# The print() function is a so-called in-built function. This means that no matter which other things
# you may be working with, these functions are always available to use. There is a number of other
# in-builts which you will find extremely useful. For example, most math is done using a single sign:

c = a + b   # addition
d = b - a   # subtraction
e = a * b   # multiplication
f = a / b   # division
g = a ** b  # power
h = b // a  # floor division
i = b % a   # modulo
j = (a+1)*b # parentheses

# Python also allows easy comparisons. A '==' checks, whether the left and right side evaluate to the
# same value. A '!=' checks whether the left and right side evaluate to different values.
# You can also use '>', '<', '>=' and '<=' for comparisons.
# When you print the result, or save it to a new variable, it will be either 'True' or 'False'.

print(a == b)
print(a != b)
k = (a == b)
print(k)

False
True
False


In [ ]:
# Because Python is your friend, it also allows you to make comparisons using 'is'. It is useful for
# things other than math, too! You can compare pretty much anything.

print(a is b)
print("Hello" is "hello")

False
False


<>:5: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
<>:5: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
/tmp/ipython-input-2135152865.py:5: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  print("Hello" is "hello")


In [ ]:
# Another common built-in function is 'len'. 'len' gives you the length (surprise) of anything
# you use it on:

print(len("Hello"))

# The string "Hello" has 5 characters, hence its length is 5.

# Python has a lot of these and we discuss those functions as we need them.

5


### Chapter 0.2: "Functions and conditions"

Next, we will look at functions. A function is a piece of code that you know you will use often, but which you do not want
to constantly rewrite and copy. The only thing you need to know about functions for now, is that they take *some* input and produce
*some* output. We define functions with the 'def' keyword.

Any function has a **signature** which shows its name and what sort of inputs it accepts:

```python
def myfunc(a, b):
  return a * b
```
While python will not complain about this definition, it makes sense to include a variety of other information, such as so-called type hints and documentation.

```python
def myfunc(a: int, b: int) -> int:
  """
  This is a short description of the function's inputs and returns
  """
  return a * b
```

In [ ]:
def myfunc(a: int, b: int) -> int:
  """
  This function returns the product of two integers a and b.
  """
  return a * b

myfunc(2, 3)

6

In [ ]:
# Let's try putting in something that isn't a number, but rather text (called a string).

myfunc('3', 3)

'333'

You may notice that the function works, even if we input arguments that are not integers such as floats or even strings and lists. While this flexibility is among the things that make python great, they can also be very confusing for beginners. While type hints can be a part of a function's signature, they are not enforced by the compiler.

When a function accepts multiple data types, we can let others know by relaxing the type hints:

```python
def myfunc(a: int | float, b: int | float) -> int | float:
  """
  This function returns the product of two numbers a and b.
  """
  return a * b
```

Not all functions have inputs or return something:

This is a perfectly valid function:

```python
def no_inputs() -> int:
  some_var = 5
  return some_var
```

as well as this one:

```python
def no_returns(some_arg: str, some_other_arg: str) -> None:
  print(f'The inputs to this function call were {some_arg=} and {some_other_arg=}')
```

#### Default arguments
Sometimes it can be convenient to have a default value for an argument, reducing the amount of boilerplate code you have to write.

In [ ]:
def get_temperature(unit: str = 'Celsius'):
  if unit == 'Celsius':
    print('The current temperature is 24°C')
  elif unit == 'Fahrenheit':
    print('The current temperature is 75.2F')

In [ ]:
# Exercise
# Write a function that outputs 'Hello {username}! Glad that you are here!'

def greet() -> None:
  #raise NotImplementedError
  username = 'SveDrey'
  print(f'Hello {username}! Glad that you are here!')
greet()

Hello SveDrey! Glad that you are here!


In [ ]:
# Exercise
# Extend the function such that it can greet two people

def greet_2() -> None:
  #raise NotImplementedError
  username_1 = 'SveDrey'
  username_2 = 'User2'
  print(f'Hello {username_1} and {username_2}! Glad that you are here!')

greet_2()

Hello SveDrey and User2! Glad that you are here!


In [ ]:
# Exercise
# How can we greet any number of people?

def greet_any() -> None:
  #raise NotImplementedError
  list_names = ['Svenja', 'Anna', 'Dustin']
  names = ", ".join(list_names)
  print(f'Hello {names}! Glad that you are here!')


greet_any()

Hello Svenja, Anna, Dustin! Glad that you are here!


#### Scopes

A scope is a textual region of a Python program where a namespace is directly accessible. “Directly accessible” here means that an unqualified reference to a name attempts to find the name in the namespace.

Although scopes are determined statically, they are used dynamically. At any time during execution, there are 3 or 4 nested scopes whose namespaces are directly accessible:

the innermost scope, which is searched first, contains the local names
the scopes of any enclosing functions, which are searched starting with the nearest enclosing scope, contain non-local, but also non-global names
the next-to-last scope contains the current module’s global names
the outermost scope (searched last) is the namespace containing built-in names
If a name is declared global, then all references and assignments go directly to the next-to-last scope containing the module’s global names. To rebind variables found outside of the innermost scope, the nonlocal statement can be used; if not declared nonlocal, those variables are read-only (an attempt to write to such a variable will simply create a new local variable in the innermost scope, leaving the identically named outer variable unchanged).

Usually, the local scope references the local names of the (textually) current function. Outside functions, the local scope references the same namespace as the global scope: the module’s namespace. Class definitions place yet another namespace in the local scope.

It is important to realize that scopes are determined textually: the global scope of a function defined in a module is that module’s namespace, no matter from where or by what alias the function is called. On the other hand, the actual search for names is done dynamically, at run time — however, the language definition is evolving towards static name resolution, at “compile” time, so don’t rely on dynamic name resolution! (In fact, local variables are already determined statically.)

Let's take a look at some examples:

In [ ]:
# global scope
my_var: int = 5
print(f'{my_var=}')

def foo():
  # local scope
  my_var = 10
  print(f'{my_var=}')

foo()
print(f'{my_var=}')

my_var=5
my_var=10
my_var=5


Initially this might seem confusing, but as long as you keep track where you define variables, scopes become a second nature to you.

In [ ]:
test_var: str = 'Tom'

def test_function(test_var: str = 'Tim') -> str:
  test_var = 'Till'
  return test_var

# What will this print?
print(test_function(test_var))
print(test_var)

Till
Tom


#### `*args` and `**kwargs`

Sometimes you need to pass an arbitrary combination of arguments to a function. Instead of passing them in a list, we can make use of the `*args` notation.

In [ ]:
def flexible_function(*args) -> None:
  for arg in args:
    print(arg)

flexible_function(1, 2, 3, 4, 5)

1
2
3
4
5


In [ ]:
# Exercise
# Write a function that sums an arbitrary number of inputs without using sequences or the sum() built-in function

def flex_sum(*args) -> int | float:
  for arg in args:
    print(arg)
  #raise NotImplementedError

flex_sum(1, 2, 3, 4)
flex_sum(0, 1, 2)
flex_sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
#*args gibt unterschiedliche Anzahl an Argumente in eine Funktion über

1
2
3
4
0
1
2
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


However, sometimes it is necessary to have context to certain argument. Say you want to write a function that writes a table reservation, but leaves room for custom remarks. In this case you can use the `**kwargs` notation:

In [ ]:
def table_reservation(num_people: int, **kwargs) -> None:
  print(f'You made a reservation for {num_people}\nYour extra wishes are:')   #\n = neue Zeile
  for key, value in kwargs.items():
    print(f'{key}\t:\t{value}')     #\t = Tabelarisch aufgelistet

table_reservation(4, vegetarian=True, outside_table='Yes please!')

You made a reservation for 4
Your extra wishes are:
vegetarian	:	True
outside_table	:	Yes please!


#### Lambda expressions

Lambda expressions in python produce small, anonymous functions that follow a more strict syntax. In theory, you can avoid using lambda expressions altogether, but they are undeniably handy in certain situations.

In [ ]:
list_of_fruits: list = ['Apple', 'Banana', 'Pear', 'dragonfruit', 'cherry', 'Apricot']
# We can easily filter this list using a nifty lambda expression:
uppercase_fruits: list = list(filter(lambda x: x[0].isupper(), list_of_fruits))   #prüft ob der erste Bchstabe groß oder klein geschrieben ist
print(uppercase_fruits)

['Apple', 'Banana', 'Pear', 'Apricot']


#### Decorators

What Are Decorators in Python?

A decorator in Python is a higher-order function that modifies or extends the behavior of another function without modifying its actual code. Decorators are commonly used for logging, timing execution, enforcing access control, memoization (caching), and more.

How Do Decorators Work?

A decorator is a function that takes another function as an argument, wraps it in another function (usually called wrapper), and returns the wrapped function.


In [ ]:
import time

def timing_decorator(func):
    """Decorator that times the execution of a function."""
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"Function {func.__name__} took {elapsed_time:.6f} seconds to execute.")
        return result
    return wrapper

# Example usage
@timing_decorator
def example_function():
    time.sleep(1)
    return "Finished"

# Run the function
example_function()

Function example_function took 1.000198 seconds to execute.


'Finished'

### Chapter 0.3: "Import statements"

Often, code that we want to write already exists. In other cases, maybe the code we want to write is just too hard for
us to write ourselves. In such cases, we 'import' code. Typically, this is done once, at the start of any program you
write. As a general rule, it is good to import only the things you need. However, importing things you don't need is
fine, too.

In [ ]:
# If we want to import code from a library called 'numpy', we do it like this:
import numpy
import math

# We can even give it a new name, if we are particularly lazy. Now, instead of
# calling a function by the name 'numpy.array', we can simply write 'np.array'.
import numpy as np

# If we only want something very specific, we can import one or several methods
# like so:
from numpy import array, random

Many of these libraries come pre-installed with Python, but are not always loaded, such as the os or sys libraries. Others must be installed first and can then be used, a process that happens automatically in Colab if you don't already have them.

We can even make our own code, and import it, given some conditions:
1) The file must be a regular .py file. While it is possible to import from Jupyter Notebooks (the thing we are working in right now), it is not recommended.
2) The computer must know where to look for the files. You can extend the places that vscode will search by providing a custom environment, or even at runtime. Below, we show the latter method.

In [ ]:
import sys
# Look for importable stuff in the current directory, ...
sys.path.append("./")
# ... look in directory above, ...
sys.path.append("../")
# ... and check some other places.
sys.path.append("/some/other/place")




### Chapter 0.4: "Data types"

Python has *a lot* different data structures, many of which we will learn about later.
However, some are particularly useful. Even outside of the context of machine learning, it is good to know these.

#### Chapter 0.4.1 "Lists"

In [ ]:
# The most common data type anywhere is probably the List. An explanation of what a List is works best when showing it.
# This is a List:

my_first_list = [2, 4, 6, 8]
print(my_first_list)

# You can have anything you want inside of a List - integer numbers, floating point numbers, strings, booleans, even
# things like functions and other lists! This is a completely valid list:

#(booleans = True/False)
my_second_list = [2, "4", "six", 8.0, my_first_list]
print(my_second_list)

[2, 4, 6, 8]
[2, '4', 'six', 8.0, [2, 4, 6, 8]]


In [ ]:
# You can look at elements of your list by looking at the list at a specific index.
# Note that when we look at anything like a list in Python, we start our indexing at 0, not 1.

# This will print the first element of our list, the integer 2:
print(my_first_list[0])
# This will print the second element of our list, the integer 4:
print(my_first_list[1])

2
4


In [ ]:
# We can even start counting from the end and go towards the start.
# This will print the last element of our list, the integer 8:
print(my_first_list[-1])
# This will print the second-to-last element of our list, the integer 6:
print(my_first_list[-2])

8
6


In [ ]:
# We can also look at parts of our list. Lets say that I want the first 2 values of my list.
# This will give me a smaller list, containing the first two elements of my list:
my_shorter_list = my_first_list[0:2]
print(my_shorter_list)
# The notation with the colon means "start at index 0, stop at index 2". Note that the stopping
# point is NOT part of the new list.

[2, 4]


In [ ]:
# Lists can also do other neat things.
my_first_list = [2, 4, 6, 8]
my_second_list = [2, "4", "six", 8.0]

# They know how long they are:
print(len(my_first_list))

4


In [ ]:
# They know whether something is in them or not:
if "six" in my_second_list:
    print("Yup, 'six' is in my list.")

Yup, 'six' is in my list.


In [ ]:
# You can add new values to a list by 'appending' them:
my_first_list.append(10)
print(my_first_list)

[2, 4, 6, 8, 10]


In [ ]:
# You can overwrite old elements with new ones:
my_first_list[0] = 3
print(my_first_list)

[3, 4, 6, 8, 10]


In [ ]:
# You can even stick together two lists, by 'extending' a list:
my_first_list.extend(my_second_list)
print(my_first_list)

[3, 4, 6, 8, 10, 2, '4', 'six', 8.0]


#### Chapter 0.4.2: "Dicts"

In [ ]:
# Another very common data type is the dict, or dictionary. It is somewhat similar to a list,
# but not quite the same.
# What makes dictionaries special is the way its contents are accessed. A dictionary has so-called
# keys and values. To every key belongs a specific value. Keys are always unique, but values don't
# have to be.

# A typical dictionary looks like this:
shopping_list = {"apples": 6, "bananas": 4, "strawberries": 20}
print(shopping_list)

# We can look at its contents with almost the same indexing we used for lists. Instead of looking
# for index 0 or index 1 or something like that, we give the dictionary a key and ask it what the
# value for this key is:
num_apples = shopping_list["apples"]
print(num_apples)

# The keys and values in a dictionary can be almost anything you want. However, it is much easier
# and much less dangerous, if you use only strings or integers as keys. For values, you can do
# whatever you want.

{'apples': 6, 'bananas': 4, 'strawberries': 20}
6


In [ ]:
# If you want to add something to an existing dicitonary, you can do so by providing the key and value.
# Changing an existing value in a dictionary works the same way:
shopping_list["apples"] = 5
shopping_list["pretzels"] = 3
print(shopping_list)

{'apples': 5, 'bananas': 4, 'strawberries': 20, 'pretzels': 3}


In [ ]:
# If you want to extend your dictionary, you can do so using .update:
sweets = {"bonbons": 30, "chocolate_bars": 2}
shopping_list.update(sweets)
print(shopping_list)

{'apples': 5, 'bananas': 4, 'strawberries': 20, 'pretzels': 3, 'bonbons': 30, 'chocolate_bars': 2}


In [ ]:
# A dictionary knows its own length:
print(len(shopping_list))

6


In [ ]:
# It also knows whether something is in it or not:
if "apples" in list(shopping_list.keys()):
    print("Apples are on my shopping list.")

Apples are on my shopping list.


In [ ]:
# You can even delete parts of your dictionary:
del(shopping_list["bananas"])
print(shopping_list)

{'apples': 5, 'strawberries': 20, 'pretzels': 3, 'bonbons': 30, 'chocolate_bars': 2}


#### Chapter 0.4.3: "Tuples"

In [ ]:
# Tuples are a bit like lists. However, they have one key difference: Once you make a tuple,
# you can't change it anymore. They are 'immutable'.
# This may sound strange and plainly less useful than lists, but it can sometimes be faster
# to use tuples over lists. There is also another feature you will find out about in a bit.

# You can declare a tuple like this:
my_tuple = (1, 2)

# Just like lists and dicts, you can put basically anything into a tuple:
another_tuple = ("one", 2.0, 3, "4")

In [ ]:
# You can look at parts of your tuple just like with lists:
print(another_tuple[0])
print(another_tuple[0:3])

one
('one', 2.0, 3)


In [ ]:
# You can check if something is in the tuple:
if "4" in another_tuple:
    print("Yup, '4' is in my tuple.")

Yup, '4' is in my tuple.


In [ ]:
# Now, what are tuples actually good for?
# Python comes with a neat feature called tuple unpacking. You can see this feature in action below:

my_tuple = (1, 2, 3)
a, b, c = my_tuple
print(a)

# Python just saw that I wanted to declare three variables. On the other side of the '=' was a tuple
# with three entries, and Python assigned the first entry to my first variable, second to second, etc.

1


In [ ]:
# Why is this useful?
# Let's say I have a function that calculates several things for me. I want to get back all the
# different outputs, and I will be using them for separate things. Tuple unpacking will take the
# output from the function and try to 'unpack' it into however many variables I suggest:

def my_function(a: int, b: int):
    c = a + b
    d = a - b
    return c, d

e = 3
f = 2

# Here I suggest g and h as variables, and tuple unpacking will expect my function to give back
# a tuple of length two.
g, h = my_function(a = e, b = f)
print(g)
print(h)

5
1


#### Chapter 0.4.4: "Numpy Arrays"

In [ ]:
# Numpy arrays are also a little bit like lists. However, there are some differences.
# Let's make one. We create an array by calling the numpy.array function. The only
# argument this function absolutely needs is a list.

my_array = np.array([2, 4, 6, 8, 10])
print(my_array)

# We can also tell numpy to make us an array, for exampling by telling it randomly
# roll us some integers

my_random_array = np.random.randint(low = 0, high = 5, size = 5, dtype = np.int8)
print(my_random_array)

# Notice the 'dtype'? Every numpy array has a dtype, and every element inside our
# array is definitely of that type. In this case, all elements in our array are 8-bit
# integers.

[ 2  4  6  8 10]
[2 3 1 4 2]


In [ ]:
# We can do some of the things with a numpy array that we could do with lists.
# In fact, it makes sense to think of numpy arrays as lists, which are only used
# for maths - in essence, numpy arrays are matrices.

# They do most of the stuff that lists do, such as ...
# ... accessing elements:
print(my_array[0])

2


In [ ]:
# ... slicing:
print(my_array[0:3])

[2 4 6]


In [ ]:
# ... length:
print(len(my_array))

5


In [ ]:
# They also have a multitude of other features, which we will look at in the future.
# One of them is particularly important however. Numpy arrays can have an arbitrary
# number of dimensions. For example:
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_other_matrix = np.zeros(shape = (3, 3))
print(my_matrix)
print(my_other_matrix)

# You can check the shape of a numpy array by checking its shape attribute like so:
print(my_matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [ ]:
# Just like real matrices in maths, numpy arrays come with a ton of useful features,
# such as transposing, summing, matrix multiplication, etc. Many of these will also
# be available in PyTorch, which we will ultimately use for our machine learning.

# Here are some examples.
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Transposition
print(my_matrix.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [ ]:
# Reshaping
print(np.reshape(my_matrix, (2, 6)))    # np.reshape(Matrix, (Zeilen,Spalten))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# Flattening into a vector
print(my_matrix.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Operations along a dimension
print(np.max(my_matrix, axis = 0))        #axis = 0 -> vertikal ; axis= 1 -> horizontal
print(np.max(my_matrix, axis = 1))        #max = suche Maximum der Spalte/Zeile

# It is impossible to know all of them by heart. What you need to know is how to
# express what you want to do in as concrete terms as possible. If you can do that,
# you will find any function you need on google or in the numpy documentation.

[10 11 12]
[ 3  6  9 12]


In [ ]:
# Try to create some lists, dictionaries, tuples and numpy arrays of your own.
# If you know a math operation that you want to see, maybe a dot product, try
# to find the function in numpy and see if it works the way you think it should!


#list:
my_list = [17, 11, 2001]
print(f'Im born in {my_list[2]}')

#dictionaries
dic = {'student': 30, 'teachers': 3}
total = dic['student'] + dic['teachers']
print(f'Total people in the classroom {total}')

#tupels
tup_1 = (1, 2, 4, 5)
tup_2 = (4, 0.7, 3.9)
a, b, c, d  = tup_1
e, f, g = tup_2

print(f*d)
print(f/d)

#Array
matrix_1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(matrix_1)
matrix_2 = np.array([[4, 6, 2], [3, 1, 0], [6, 7, 2]])
print(matrix_1 * matrix_2)

Im born in 2001
Total people in the classroom 33
3.5
0.13999999999999999
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[4 0 0]
 [0 1 0]
 [0 0 2]]


### Chapter 0.5: "Loops and Iterables"

Now that we've got some of the building blocks and know how to write code, let's do some problem solving.

When you buy groceries, you put your perishable goods into the fridge (or so I hope). But, you don't close
your eyes, take an item out of your bag and put it into the fridge and do this exactly three times or
exactly 5 times. You always take the next thing in the bag and put it into the fridge, until the bag is
empty, and you don't think about how many things you actually just put into the fridge exactly.

The exact same pattern exists in programming and is one of the most common patterns in existence. This
behaviour is called a 'loop'. Different languages handle loops slightly differently, but in broad strokes,
they all do the same thing. Let's build some.

In [ ]:
# The most common loop in python is the 'for' loop. It consists of two parts. An iterable
# and the loop segment. An iterable, in layman's terms, is something you can iterate over.
# For example, a list like [1, 2, 3] is an iterable. The first element is a 1, the second
# is a 2, and so on. An iterable is capable of giving you (at the very least) the next
# item, and telling you when it has no more items.
# The loop segment is code that is executed for each iteration. The only rules are that you
# cannot change your iterable during the iteration, and that your code must be indented.

# Let's look at a practical example:
shopping_list = ["Apples", "Bananas", "Strawberries"]
for item in shopping_list:
    print(item)

# Our loop iterates over the iterable, the shopping list.
# On every iteration, it takes the next item on the list and puts it into the variable 'item'.
# In our loop segment, we simply print the 'item' variable.

Apples
Bananas
Strawberries


In [ ]:
# You can (and generally will) also access any other variables in your loop:
numbers = [1, 4, 9, 16]
sum = 0
for number in numbers:
    sum = sum + number
print(sum)

30


In [ ]:
# Behind lists, one of the most common iterables is probably the range object:
for n in range(10):
    print(n)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# An alternative to having either the content of an iterable or a number, is using 'enumerate',
# which gives you both of them:
for index, item in enumerate(numbers):
    print(index, item)

0 1
1 4
2 9
3 16


In [ ]:
# Sometimes, you have two iterables and want to do something with both of them.
# For example, maybe you have two lists of numbers, and want to pair them up to multiply them,
# like in a dot product. For such use cases, 'zip' exists.
vector_a = [1, 2, 3]
vector_b = [3, 0, 2]
sum = 0
for ai, bi in zip(vector_a, vector_b):
    sum = sum + ai * bi
print(sum)

9


In [ ]:
# Loops also have some functionality to let you skip an iteration or stop the loop altogether.
# The following function determines the smallest integers divisor of any integer in a very
# naive fashion. We loop over all potential divisors from 0 to our dividend.

# If the divisor is 0 or 1, we want to skip the current iteration. We do so with the keyword
# 'continue'. The next iteration starts at the start of the for-loop's indentation

# If the dividend modulo the divisor is 0, we have found our smallest divisor, and we want to
# stop iterating. We can stop the iteration using the keyword 'break'. In this case, the code
# skips ahead to where the indentation of the for-loop ends (see below).

def find_smallest_divisor(dividend: int):
    for divisor in range(dividend):
        # continue jumps here
        if divisor == 0 or divisor == 1:
            continue
        if dividend % divisor == 0:
            break
        if divisor== dividend-1:
            print(f"Looks like {dividend} is a prime!")
            return dividend
    # break jumps here
    return divisor

print(find_smallest_divisor(9))
print(find_smallest_divisor(17))

3
Looks like 17 is a prime!
17


In [ ]:
# One final thing that makes iterables cool: Progress bars.
# Who doesn't like a good progress bar steadily filling up?
# tqdm is a package that lets you display progress when
# iterating over an iterable wrapped in tqdm.

from tqdm.auto import tqdm
import time

my_numbers = [1, 2, 3, 4, 5]
my_squares = []
for number in tqdm(my_numbers):
    my_squares.append(number ** 2)

  0%|          | 0/5 [00:00<?, ?it/s]

In [ ]:
# Try to make yourself a small toy problem and solve it using a for loop.

# If your first thought was "That is not a sensible prime number detector
# up there", maybe that could be your task :)






### Chapter 0.6: "List Comprehensions"

Python contains a nifty little feature called List Comprehension. This allows you to write a piece of code that
would otherwise be a little unwieldy in a single short expression.

In [ ]:
# The following two segments of code are equivalent and both create a list containing
# the squares of the digits from 0 to 9:

# Method 1
squared_digits = []
for x in range(10):
    y = x ** 2
    squared_digits.append(y)
print(squared_digits)

# Method 2
squared_digits = [x ** 2 for x in range(10)]
print(squared_digits)

# We have essentially just executed an entire loop inside of the square brackets of
# our list, at the moment of its creation.

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
# This tool also works on other data types, such as tuples or dictionaries:
squared_digits = {x: x**2 for x in range(10)}
print(squared_digits)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


In [ ]:
# It can even handle more complex instructions, such as conditionals.
# Let's make a list that contains only digits that are even.
only_even_digits = [x for x in range(10) if x % 2 == 0]
print(only_even_digits)

[0, 2, 4, 6, 8]


In [ ]:
# Let's make one that containts even and odd digits, but even digits are squared.
square_even_digits = [x ** 2 if x % 2 == 0 else x for x in range(10)]
print(square_even_digits)

# List comprehensions are an extremely powerful tool which is worth practicing a little.

[0, 1, 4, 3, 16, 5, 36, 7, 64, 9]


In [ ]:
# Try to make a list containing the prime numbers up to 100 by using a list comprehension.
# If you want to challenge yourself, try to do so without using any functions to check
# whether a given number is prime. You can find a solution below.

prime_numbers = [x for x in range(2, 100) if all( x % i != 0 for i in range(2, x) ) ]
print(prime_numbers)



[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [ ]:
import numpy as np
# Solution with functions:
def is_prime(dividend: int):
    # If the dividend is smaller than 2, it can't be prime
    if dividend < 2:
        return False
    # If the dividend is two, it is a prime.
    elif dividend == 2:
        return True
    else:
        # Try all divisors starting at 2 and up to the square root of the dividend
        for divisor in range(2, max(3, int(np.sqrt(dividend)+1))):
            if dividend % divisor == 0:
                return False
            else:
                pass
                # 'pass' means 'do nothing' - instead of writing
                # else: pass, you can also simply write nothing
        # If we have gotten past the loop without finding a divisor
        # (and thus returning it), the number is a prime.
        return True

primesC = [x for x in range(1, 101) if is_prime(x) is True]
print(primesC)

# Solution without non-native functions:
primesC = [x for x in range(2, 101) if len([y for y in range(2, max(3, int(math.sqrt(x)+1))) if (x % y == 0 and x != 2)]) == 0]
print(primesC)

# As a final note, we should mention that even though the second solution is maybe a little more clever
# and shorter, the first solution is actually the better one by far - you always want your code to be readable!

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### Chapter 0.7: "OS and files"

When working with any sort of data, we will not only have to work with lists or arrays we made ourselves. Naturally, we will use pre-existing images or other data. Therefore, we need at least some passing familiarity with how our file system works, how we can open text files or images so that we can work with them.

The most common function used when working with files is open(). In order to open a file, with open() or with any other function, you need to know where the file is. You can refer to files in two ways: relative paths and absolute paths.

A relative path looks like this:
```relative_path = "./example.txt"```.
The ```.``` means "start at the current folder", the one that this notebook lives in.

An absolute path looks like this:
```absolute_path = "/Projects/AIMA/Course_Materials/Chapter_0/example.txt```.
The ```/``` at the start means that you start at the bottom of the file system, also
called "root", and then go from there.

Let's play around with some files.

In [ ]:
# First, we create some prepared files. We'll find out in a second, how this works.
with open("./example.txt", "w") as o:
    o.write("Hello World\nfoo bar")
with open("./staff.csv", "w") as o:
    o.write("name,age,gender\nFreddy,28,male\nMarie,24,female\nProf. Kleesiek,900,male")

In [ ]:
# This is how you open a file in read mode:
out = open("./example.txt", "r")

# This is how you read all lines from the text:
lines = out.readlines()

# readlines() returns a list, and each element of the list is one line of text:
for line in lines:
    print(line)

# And this is how you close it:
out.close()

Hello World

foo bar


In [ ]:
# There is also a cleaner way of opening files, the 'with' statement:

# Whatever you encapsulate in a 'with' is created for this context.
with open("./example.txt", "r") as out:
    # I can use 'out' in here:
    lines = out.readlines()

# I would not be able to use 'out' outside of this context.
# The context manager has closed 'out' for me again.
# It has also thrown it away.

# However, variables I created in the 'with' block still exist:
for line in lines:
    print(line)

Hello World

foo bar


In [ ]:
# We can also write to files.
# To do this, we open our file in write mode 'w' (which overwrites)
# or in append mode 'a' (which appends what we write to the end):
with open("./example.txt", "a") as out:
    # String writing allows some controls.
    # For example, '\n' denotes a newline, or '\t' a tab.
    out.write("\n")
    out.write("Programming is easy.\n")
    out.write("I am a god.")

# Let's confirm that writing to the file worked:
with open("./example.txt", "r") as out:
    lines = out.readlines()
for line in lines:
    print(line)

# We can also create files as we open them, even if they don't yet exist.

Hello World

foo bar

Programming is easy.

I am a god.


In [ ]:
# Now it's your turn for a moment.
# Make yourself a shopping dictionary.
# Each key is something you want to buy. Each value is the amount you want to buy.
groceries = {'apples': 3, 'Bread': 1, 'chips': 4, 'milk': 3}
# Now try to use a loop and your knowledge of open() to make a file called 'shopping_list'
# and neatly write your shopping list into the file. Which file type makes sense?
with open("./shoppping_list", "w") as file:
    for item, amount in groceries.items():
      file.write(f"{item}: {amount}\n")

with open("./shoppping_list", "r") as out:
  lines = out.readlines()
for line in lines:
  print(line)




apples: 3

Bread: 1

chips: 4

milk: 3



Next, let's check out a format called csv - comma-separated values Originally, these were text files that looked something like this:

1,2,3  
4,5,6    
7,8,9    

Nowadays, its not uncommon to also write text or more esoteric things between the commas.

Reading and writing to those files does not work differently from regular text files. However, there is several nice tools to help use this particular formatting style efficiently. For now, learning the simplest one of them will suffice.

In [ ]:
# split() is a simple method that every string is capable of.
# You specify by what delimiter the string is supposed to be split.
print("1,2,3".split(","))

['1', '2', '3']


In [ ]:
# Try to read in the staff.csv file like you have learned above.
# Using split and loops, make one list each which contains all
# names, ages and genders.

with open("./staff.csv", "r") as out:
    lines = out.readlines()
for line in lines:
  print(line)





name,age,gender

Freddy,28,male

Marie,24,female

Prof. Kleesiek,900,male


In [ ]:
# So, what do we do if we don't know where our files live, or what
# their names are? It is quite common to have so much data, that
# you cannot know all of it, nor manually write it.

# The os package provides us with the tools that we need.
import os

# os.listdir() tells us the contents of a directory. It returns a list.
# The "./" is the name of the directory to search and means 'wherever
# we are right now.'
output = os.listdir("./")
print(output)

['.config', 'example.txt', 'shoppping_list', 'staff.csv', 'sample_data']


In [ ]:
# Notice that there is files and directories in the output.
# Also, we have been told their names, but never their full paths.

# Let's get some full paths using os.path.join().
# os.path.join() attaches parts of a file's path to one another,
# adding "/" as needed to make it a correct path.
full_paths = [os.path.join(os.getcwd(), p) for p in output]
print(full_paths)

['/content/.config', '/content/example.txt', '/content/shoppping_list', '/content/staff.csv', '/content/sample_data']


In [ ]:
# We can filter the output to contain only directories or files
# using isdir and isfile:
only_files = [p for p in full_paths if os.path.isfile(p)]
only_dirs = [p for p in full_paths if os.path.isdir(p)]
print(only_files)
print(only_dirs)

['/content/example.txt', '/content/shoppping_list', '/content/staff.csv']
['/content/.config', '/content/sample_data']


Just as with any other package, os offers a ton of utility you will learn about at some point in time. For now, this knowledge will hopefully suffice.

### Chapter 0.8: "Try and Except"

We've seen earlier what happens if we break our code. Python will try to execute anything you write and only upon execution realize that maybe it was complete nonsense from the start. Sometimes such a mistake is easy to spot. Sometimes, it is buried within layers and layers of code and almost invisible. Worse, sometimes it's not even you who made the mistake!

When you work with large amounts of data, you can not always guarantee that everything goes smoothly. Maybe one of your 3 million images has the wrong shape, or maybe it doesn't have an RGB channel, maybe the file is simply broken or the website you are downloading it from suddenly stops responding. How can you prevent an error that you don't know about in advance?

Enter 'Try and Except'.

Similar to 'If and Else', 'Try and Except' allows you to write code and execute it on some condition. However, for 'Try and Except', this condition is that Python is throwing an Exception. The 'Try' part wraps the code you want to run. The 'Except' part contains code that is executed if the 'Try' code fails.

In [ ]:
# Let's make some toy code using a Try/Except block.
# We want to make a new list, which contains the result of a division.

my_cool_number = 6
divisors = [3, 2, 1, 0, "a"]

new_numbers = []
for d in divisors:
    new_numbers.append(my_cool_number / d)
print(new_numbers)

ZeroDivisionError: division by zero

In [ ]:
# Uh oh. We tried dividing by zero, which throws a ZeroDivisionError.
# Let's say we don't mind having an infinity in our list:

new_numbers = []
for d in divisors:
    try:
        new_numbers.append(my_cool_number / d)
    except:
        new_numbers.append(np.inf)

print(new_numbers)

[2.0, 3.0, 6.0, inf, inf]


In [ ]:
# We have just intercepted every possible error during the for loop and said:
# "If you see any error, just jot down infinity as the result and carry on".

# Sometimes, this is not ideal. Only when you divide by zero is the result
# going to be infinity. What if we have other errors? We can specify what kinds
# of error we want to intercept and what kinds we let through:

new_numbers = []
for d in divisors:
    try:
        new_numbers.append(my_cool_number / d)
    # We except the ZeroDivisionError specifically here
    except ZeroDivisionError:
        new_numbers.append(np.inf)
    # We except multiple kinds of error like this, by putting them into a tuple
    except (ValueError, TypeError):
        pass
    # Any kind of error we have not specifically caught is still raised,
    # crashing your program.

print(new_numbers)

[2.0, 3.0, 6.0, inf]


In [ ]:
# Try to think of some task that you could wrap in a Try/Except block and
# test it, to see if Try/Except works the way you believe it should!





### Chapter 0.9: "Classes and Inheritance"

Perhaps the most powerful object in Python is the *class*. Classes are extremely versatile and are used in pretty much every program out there, including PyTorch, which we will use for our actual machine learning exercises. Classes provide a means of bundling data and functionality together. Creating a new class creates a new type of object, allowing new instances of that type to be made. Each class instance can have attributes attached to it for maintaining its state. Class instances can also have methods (defined by its class) for modifying its state.

To learn what classes can do, the best way is to make some!

In [ ]:
# A minimal class might look like this:
class myClass:
  def __init__(self, value: int) -> None:
    self.val = value

# We can now use our above class as follows
class_object = myClass(5)

# You can access public class attributes like so:
print(f'The value of the val attribute is {class_object.val}')

The value of the val attribute is 5


Classes can not only have attributes but also so-called methods. Methods are class-specific functions that can be called similar to how attributes are accessed:

In [ ]:
class Human:
  def __init__(self, name: str, age: int) -> None:
    self.name = name
    self.age = age

  def greet(self) -> None:
    print(f'Hello there! My name is {self.name}.')

  def birthday(self) -> None:
    self.age += 1
    print(f'Happy birthday! You are now {self.age} years old.')

human = Human('Bob', 23)
human.greet()

Hello there! My name is Bob.


In [ ]:
# Exercise
# The current greeting isn't very personal. How can you greet someone by name?
class Human:
    def __init__(self, name: str, age: int) -> None:
        self.name = name
        self.age = age

    def greet_other(self, other_person):
        print(f'Hello {other_person}! My name is {self.name}.')

    def birthday(self) -> None:
        self.age += 1
        print(f'Happy birthday! You are now {self.age} years old.')

human = Human('Svenja', 23)
human.greet_other('Anna')



Hello Anna! My name is Svenja.


Classes are an important tool in any programmer's arsenal, as they can make complex relations easier to understand. If you were to implement a new class, you can even reuse other classes through the power of **inheritance**.

In [ ]:
class Student(Human):
  # Here, we tell Python that every Student is a Human and can do all the things a Human can
  def __init__(self, name: str, age: int, university: str, course: str, matriculation_number: int) -> None:
    super().__init__(name=name, age=age)
    self.university = university
    self.course = course
    self.matriculation_number = matriculation_number

  # You can also override functions of the superclass if need be
  def greet(self) -> None:
    print(f'Hello there! My name is {self.name}. I am a student at {self.university}.')

lena = Student(name = 'Lena', age = 25, university = 'UDE', course = 'Medicine', matriculation_number = 123456789)
# Since the student class inherited from Human, you can still access these attributes just like before:
print(lena.name)
lena.birthday()

Lena
Happy birthday! You are now 26 years old.


In [ ]:
# Exercise
# Add a method of your choice to the Human class and use it with the lena variable
# Remember to re-run code cells that you make changes to




#### Private attributes and methods, getters and setters

Sometimes you want to signal to other programmers that some attributes or methods are only supposed to be accessed from within the class itself. These attributes and methods are prefixed with an underscore to mark them as private. Altough python will still let you access these variables, it should come as reminder that what you are doing was not originally intended.

In [ ]:
class BankAccount:
  def __init__(self, owner: str, balance: float, currency: str = '€') -> None:
    self._balance = balance
    self.owner = owner
    self.currency = currency

  def deposit(self, amount: float) -> None:
    self._balance += amount

  def transfer(self, amount: float) -> None:
    self._balance -= amount

  def _super_secret_info(self) -> None:
    print('Lemons are just inferior limes')

account = BankAccount('Bill', 1000)
account._super_secret_info()

Lemons are just inferior limes


In [ ]:
# Sometimes it is necessary to be even more restrictive. In theory, nothing keeps you from doing this:
account._balance = 'Enough'
print(account._balance)

Enough


In [ ]:
# Obviously, this isn't great, so how can we safeguard this better?
class BankAccount:
  def __init__(self, owner: str, balance: float, currency: str = '€') -> None:
    self._balance = balance
    self.owner = owner

  @property
  def balance(self) -> float:
    return self._balance

  @balance.setter
  def balance(self, value: float) -> None:
    assert isinstance(value, (int, float)), 'Balance must be a number!'
    if value < 0:
      raise ValueError('Balance cannot be negative!')
    self._balance = value

  def deposit(self, amount: float) -> None:
    self._balance += amount

  def withdraw(self, amount: float) -> None:
    self._balance -= amount

  def _super_secret_info(self) -> None:
    print('Lemons are just inferior limes')

You have probably already noticed a few weird things about the classes
which we have been looking at until now, and it's time to talk about them.

What does 'self' mean? Why is it everywhere in the class, but seemingly
unnecessary when we call a method?

When we make a class, any function inside of it that we do not specifically
mark to be treated otherwise is a so-called *bound method*. When we have
created a class instance, that instance is passed as the first parameter
of any bound method. An example may help to understand what this means:

In [ ]:
# This
lena.greet()
# is equivalent to this
Student.greet(lena)

# Because of this, we are allowed to do these things in functions inside of a class:
def greet(self) -> None:
    print(f'Hello there! My name is {self.name}. I am a student at {self.university}.')

# To put it into simpler words: Methods of a class instance are aware of who they are.
# The Student instance lena knows its own name, age, which methods it can use.
# The methods themselves, unless explicitly told otherwise, also know lena's name, age, etc.

Hello there! My name is Lena. I am a student at UDE.
Hello there! My name is Lena. I am a student at UDE.


2. Why does the '\_\_init\_\_' function look so weird? What does it do and why does it have underscores in its name?

Some function names, like '\_\_init\_\_', are what we call 'privileged'. If you name a function in a class this way, Python will do special things with it. Here are a few examples:

- If a class contains an '\_\_init\_\_' function, the function is called when an instance of the class is initiated.
- If a class contains a '\_\_len\_\_' function, you can use the built-in len() function on an instance of your class, and it will execute its '\_\_len\_\_' function.
- If a class contains a '\_\_del\_\_' function, that function is called when an instance of the class is deleted.

Be careful about using privileged names when writing functions, particularly if they are available everywhere and not just inside of a class.

In [ ]:
class Dataset:

    def __init__(self):
        self.data = [1, 2, 3, 4]

    def __len__(self):
        # You could write anything here - you could even, as a joke, always return 3,
        # no matter what self.data actually is.
        return len(self.data)

# The '__init__' function is called here, although you don't see it.
# But self.data already exists:
my_dataset = Dataset()
print(my_dataset.data)

# The '__len__' function is called here.
print(len(my_dataset))

[1, 2, 3, 4]
4


In [ ]:
# Finally, note that the name of our classes were written with a capital letter at the start.
# This is not mandatory, but its a sort of recommendation, which can help keep your code clean.

#### Practice time!

Here are some tasks for you to try and solve. If you can't remember how something works, that is perfectly fine! Just go back a chapter or two, and look it up again. Note that none of the following tasks are graded, except for the submission to GitHub. However, we have prepared some sample solutions for you.

**Task 1**: Write a class circle that has two methods `calculate_circumference()` and `calculate_area()`. What arguments make sense to include in the `__init__()` method?

In [ ]:
class Circle:

  def __init__(self, radius):
    self.radius = radius

  def calculate_circumference(self):
    return 2 * np.pi * self.radius

  def calculate_area(self):
    return np.pi * self.radius **2

circle = Circle(3)
print(circle.calculate_circumference())
print(circle.calculate_area())

18.84955592153876
28.274333882308138


**Task 2**: Write a function count_vowels(text) that returns the number of vowels (a, e, i, o, u) in a given string.

In [6]:
def count_vowels(string: str) -> int:
  n = 0
  for vowel in string:
    if vowel in ['a', 'e', 'i', 'o', 'u','A', 'E', 'I', 'O', 'U' ]:
      n += 1
  print(f'There are {n} vowels in the string')

example = "Everything, in this cell shoud be working"
print(count_vowels(example))

There are 11 vowels in the string
None


**Task 3**: Write a function that checks if a word is a palindrome (palindromes are words that are the same if read backwards).

In [14]:
def is_palindrome(word):
  word = word.lower()
  if word == word[::-1]:
    print(f'{word} is a palindrome')
  else:
    print(f'{word} is not a palindrome')

is_palindrome('Anna')
is_palindrome('Svenja')
is_palindrome('Ein Esel lese nie')

anna is a palindrome
svenja is not a palindrome
ein esel lese nie is a palindrome


**Task 4**: Employee and Manager

Create a class Employee with attributes name and salary. Create a subclass Manager that adds an attribute department. Override a method display_info() to include department information.

In [21]:
class Employee:
    def __init__(self, name: str, salary: float) -> None:
      self.name = name
      self.salary = salary

    def display_info(self):
      print(f"Name: {self.name}")
      print(f"Salary: ${self.salary:.2f}")

class Manager(Employee):
    def __init__(self, name: str, salary: float, department: str) -> None:
       super().__init__(name, salary)
       self.department = department

    def display_info(self):
        super().display_info()
        print(f"Department: {self.department}")

employee = Employee('Svenja', 2)
manager = Manager('Leoni', 20000, 'sales')

employee.display_info()
manager.display_info

Name: Svenja
Salary: $2.00


<bound method Manager.display_info of <__main__.Manager object at 0x7ff3a917db50>>

**Task 5**: Password validator

Write a function `validate_password(password)` that checks if a password meets the following criteria:

	- At least 8 characters long
	- Contains at least one uppercase letter, one lowercase letter, and one number
	- Returns True if valid, otherwise False

In [23]:
def validate_password(password: str) -> bool:
    if len(password) <8:
      return False

    if not any(char.isupper() for char in password):
        return False

    if not any(char.islower() for char in password):
        return False

    if not any(char.isdigit() for char in password):
        return False

    return True

password_1 = 'Hallo_1234'
print(validate_password(password_1))
password_2 = '123'
print(validate_password(password_2))

True
False


### Chapter 0.10: "Debugging"

The following code snippets will each contain a mistake. Try executing them, and figure out where the mistake is coming from and how you can fix it.

At the end of the chapter, you can find a solution with an explanation of what was wrong.

**Task 6**

In [ ]:
# We want to look at the last entry in this list
my_list = [1, 4, 9, 16]

# However, this fails:
print(my_list[4])
# Why, and how do I fix it?

**Task 7**

In [ ]:
# This is a basic cat class
class Cat:

    def __init__(self, name: str, color: str = "Black"):
        self.name = name
        self.color = color

    def meow(self, loud: bool):
        if loud is True:
            print("MEOW!")
        else:
            print("Meow!")

# This is a cat instance
my_cat = Cat(name = "Findus", color = "Tabby")

In [ ]:
# Why doesn't my cat meow when I do this?
my_cat.meow

In [ ]:
# Why do I see a "None" when I try to print the output of the meow method?
the_sound_of_a_cat = my_cat.meow(loud = True)
print(the_sound_of_a_cat)

**Task 8**

In [ ]:
# This functtion should calculate the factorial
def factorial(n):
    result = 1
    for i in range(1, n):
          result = result * i
    return result

# If we look at the result, however, we notice it is 24 instead of 120.
print(factorial(5))
# Why? Fix the function and try running it again.

**Task 9**

In [ ]:
class Car:

    def __init__(self, color: str, model: str, honk_sound: str = "HONK!"):
        self.color = color
        self.model = model
        self.honk_sound = honk_sound

    def honk():
        print(self.honk_sound)

# This car should honk. But it doesn't. Instead it throws a TypeError. Why?
my_car = Car(color = "Black", model = "Mercedes")
my_car.honk()

**Task 10**

In [ ]:
a = 10
def subtract_five(b):
    b = b - 5
subtract_five(b = a)
print(a)

# You'd think that if a is 10, and I give a to the function subtract_five,
# and then the function makes it 5, that a should be 5. Why is it 10?
# And how do I make it so the function actually makes a = 5?


**Task 11**

In [ ]:
from time import sleep

# Let's say we have some numbers. We want to add the sum of each
# pair of neighbors to the list of numbers, as well.

numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
for i, number in enumerate(numbers):
    sleep(0.5)
    print(numbers[i], numbers[i+1])
    a = numbers[i]
    b = numbers[i+1]
    c = a+b
    numbers.append(c)

# Watch in slow motion what happens. Why does it keep going?
# Will it ever stop? How do you fix this?

### Debug Task Solutions

#### Task 1

In [ ]:
import math

class Circle:

    def __init__(self, radius: float):

        self.r = radius

    def calculate_circumference(self):

        c = 2 * math.pi * self.r
        return c

    def calculate_area(self):

        a = 0.5 * math.pi * self.r**2
        return a

circle = Circle(radius = 1)
print(circle.calculate_circumference())
print(circle.calculate_area())

#### Task 2

In [ ]:
def count_vowels(string: str) -> int:

    num_vowels = 0

    # In Python, Strings are iterable, meaning I can iterate over them, character by character.
    for character in string:
        # If the current character is a vowel, count it.
        if character in ["a", "e", "i", "o", "u"]:
            num_vowels += 1

    return num_vowels

print(count_vowels("hello"))

#### Task 3

In [ ]:
def is_palindrome(word: str):

    reversed_word = word[::-1]
    if word == reversed_word:
        return True
    else:
        return False

print(is_palindrome("anna"))
print(is_palindrome("dennis"))

In case the `[::-1]` confuses you, here is a quick explanation. Most things in Python that are similar to a list or an array can use slice notation, which goes like this [start:stop:step] - Start at position start, go to position stop, with step size step. [0:3:-2] for example would give you entry 0, skip entry 1, give you entry 2, and get to entry 3 and realize it should stop. A string is very similar to a list - every element of that "list" is one of the characters. Thus, we can use slices here, too. Now, why are there no start and stop numbers in our slice, and a negative step size? If we don't provide a start number, it defaults to 0. If we don't provide a stop number, it goes over the entire sequence. And a step size of -1 simply means instead of starting at 0, and going higher, we start at the last element, and go lower.

#### Task 4

In [ ]:
class Employee:

    def __init__(self, name: str, salary: int):

        self.name = name
        self.salary = salary

    def display_info(self) -> str:

        print("Name: ", self.name)
        print("Salary: ", self.salary)

class Manager(Employee):

    def make_boss_of_department(self, department: str):

        self.department = department

    def display_info(self) -> str:

        print("Name: ", self.name)
        print("Salary: ", self.salary)
        print(f"I am the boss of the {self.department} department.")

the_boss = Manager(name = "George", salary = 1000000)
the_boss.make_boss_of_department("Research and Development")
the_boss.display_info()

#### Task 5

In [ ]:
def validate_password(password: str):

    # Check the length
    if len(password) >= 8:
        long_enough = True
    else:
        long_enough = False

    # We could also shorten this to one line
    long_enough = (len(password) >= 8)

    # If my password, converted to all lowercase, is different from, it had at least 1 uppercase character
    has_uppercase = (password != password.lower())
    # If my password, converted to all uppercase, is different from, it had at least 1 lowercase character
    has_lowercase = (password != password.upper())
    # To check for numbers, we could use the any() function, which returns if the condition is true for ANY element of an iterable
    has_number = any([character.isdigit() for character in password])

    # Everything must be true
    if long_enough and has_uppercase and has_lowercase and has_number:
        return True
    else:
        return False

print(validate_password("hello"))
print(validate_password("hello4"))
print(validate_password("Hello"))
print(validate_password("Hello4"))
print(validate_password("BigGeniusPassword12"))

#### Task 6

This code snippet throws an IndexError because you are trying to access an index that doesn't exist. In Python, the indices of iterable objects (for example the list [1, 4, 9, 16]) are counted starting from 0. This means that the indices 0, 1, 2, and 3 are valid.

An even better solution than calling print(my_list[3]) would be to call print(my_list[-1]). Python considers -1 the last index of an iterable, -2 the second-to-last, and so on.

#### Task 7

`my_cat.meow` is a method of `my_cat`. If you want to call a method, just like other functions, you must use parentheses:
`my_cat.meow(loud = True)`.

Just like regular functions, class methods can return something. In fact, they always return something! If you do not tell your function to return anything, it will assume you want to return nothing. Writing
```
def do_nothing():
   sleep(1)
   return None
```
is equivalent to writing
```
def do_nothing():
   sleep(1)
```

If you wrote
```
x = do_nothing()
print(x)
```
you would always see "None" get printed. This is what happens in Task 2 as well.

#### Task 8

The factorial function is "forgetting" to multiply by 5 in this example. In fact, it would always "forget" to multiply by the last number it should multiply by. This is because range(a, b) covers the values from a to b, but not b itself. The correct expression for the task would be `range(1, n+1)`.

#### Task 9

```
def honk():
    print(self.honk_sound)
```
should instead be
```
def honk(self):
    print(self.honk_sound)
```

What happens is that the function we defined wants no inputs. But since its a bound method of the Car class, when we call it, the function is implicitly given self as the input. The error message hints that this is the case. Our function *wanted* 0 arguments, but will always be given 1 inside of the class.

#### Task 10

This concept is called Scope.

The variable b only exists inside of this function. We say "b exists only in the local scope". Meanwhile, "a exists in the global scope". Hence, inside the function we only know about b, but not about a, while outside the function, we know about a, but not about b. If we tried to print b right after pringting a, Python would tell us that we're trying to print something that doesn't exist.

Note that its absolutely possible for a variable to be made available in a different scope. For example, you can bring b from the function's local scope to the global scope, simply by returning b at the end:
```
a = 10
def subtract_five(b):
    b = b - 5
    return b
c = subtract_five(b = a)
print(a)
print(c)
```
You will find that both a and c are printable, because this time, we have brought the b from the function and then said "call this 'new thing' c." If we instead said ```a = subtract_five(b = a)```, we would set a to 5.

#### Task 11

We have just created an infinite iterator. We append to the end of the list while we are reading from it. During every step, we add one new number and use one old number for the last time, and this will go on forever. Whenever your code seems to not do anything but takes forever, or prints things into the console at incredible speed, without looking like it will stop, something like this might have happened.

How can we stop this?
- Make sure you don't change the iterable you are currently using (such as our original list of numbers), unless that is explicitly what you want.
- Use Dictionaries. Dictionaries simply don't allow you to change them while you are iterating over them, so this will never happen.

### Chapter 0.11: "Git(Hub)"

Git is a so-called Version Control System. It is used to manage programming projects, both for multiple people and when you work alone.

The typical workflow in Git looks like this:
- *Clone* a project, or *pull* the most up-to-date state of the project onto your machine
- Write some new code, or make some new files
- *Add* your code/files to a *commit*
- *Push* that *commit* to GitHub

Git is different from simply saving code/files. Instead of overwriting files, Git only tracks *changes* made to a file. That way, if you need to go back because you made a mistake, you can simply *revert* changes. It is also useful for when you accidentally delete files, as anything pushed to GitHub now also lives on the GitHub servers, meaning you can always get it back.

In this course, we manage the handing out and submission of exercises via GitHub. This way, we can be sure about the date and time you handed in your solutions, have them all gathered in a central location, and you can save your progress so that you do not lose it.

Thanks to Google Colab's Git integration, we don't even have to learn the entire tool. To submit your solutions, simply navigate to **File** > **Save** > Select your git repository/branch. We recommend to push to GitHub often. It's a good habit, and eventually could mean the difference between accidentally deleting a week's worth of hard work and being able to spend your weekend on your favorite hobby. You can commit anything you like - we will only look at the version you show us, so don't be afraid to push code that doesn't work to GitHub.

**Task 12** (1 point): Push the notebook with your solutions to your GitHub. Please take care to push the code to your *own* GitHub, not to the aima_seminar GitHub. If you do, everyone can see your code, which we don't want :)